version: "3.8"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: macellum
      MYSQL_DATABASE: macellum
      MYSQL_USER: macellum
      MYSQL_PASSWORD: macellum
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on: [mysql]

volumes:
  mysql_data:
